src/Entity/Property.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Picture;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'A prévoir',
        3 => 'Pas de chauffage'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 5, max= 255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range( min = 10, max = 100000)
     *      
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{2}/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image( mimeTypes = { "image/png",   "image/jpeg", "image/jpg" })
     * })
     * 
     */
    
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision= 6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision= 7)
     */
    private $lng;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    
    public function __construct()
    {  
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }
    
    /**
     * getSlug le titre de nos publications
     *
     * @return string
     */
    public function getSlug(): string
    {
        return (new Slugify())->Slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }
    
    /**
     * getFormattedPrice pour factoriser le prix des biens
     *
     * @return string
     */
    public function getFormattedPrice(): string
    {
        return number_format($this->price,  0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }
    
    /**
     * getHeatType 
     *
     * @return string le type de chauffage qui est utilisé.
     */
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
            $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function getPicture():?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
        return $this->pictures->first();
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of pictureFiles
     */ 
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * Set the value of pictureFiles
     *
     * @return  self
     */ 
    public function setPictureFiles($pictureFiles)
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }



}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class, 
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            
            //pour uploader plusieurs photos
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('sold')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            //pour traduire les champs de nos labels du formulaire
            'translation_domain' => 'forms'
        ]);
    }
    
    /**
     * getChoices permet de récupérer les valeurs de notre constance
     *
     * @return void
     */
    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $key => $value) {
            $output[$value] = $key;
    }
    return $output;
}

}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use App\Notification\ContactNotification;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{    
   
    private $repository;    
    private $em;
    
    public function __construct(PropertyRepository $repository, ManagerRegistry $em)
    {
        $this->repository = $repository;
        $this->em = $em;

    }
    
    /**
     * @Route("/biens", name="property.index")
     * 
     * @return Response liste l'ensemble des biens de l'application
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        
        //traitement de la recherche d'un bien
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class,  $search);
        $form->handleRequest($request);

        //système de pagination
        $properties = $paginator->paginate(
        $this->repository->findAllVisibleQuery($search),
        $request->query->getInt('page', 1),
        12);
        
        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            //pour rendre le boutton actif au clique mais il sera modifier
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()

        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     *
     * @return Response afficher les détails d'un bien en particulier
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification):Response
    {
       
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

         //création du formulaire de contact
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        

        //traitement de la requête 
        if ($form->isSubmitted() && $form->isValid()) {
            //traiment de l'envoie dans le classe ContactNotification
            $notification->notify($contact);
            $this->addFlash('success', "Message envoyé, il vous repondra dans les brefs délais!");
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('property/show.html.twig', [
            'controller_name' => 'PropertyController',
            'property' => $property,
            //pour rendre le boutton actif au clique mais il sera modifier
            'current_menu' => 'properties',
            'form' => $form->createView()
            ]);

    }
}

templates/property/_property.html.twig
<div class="card mb-5" >
    {% if property.picture %}
        <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% else %}
        <img src="{{ '/images/empty.jpg' | imagine_filter('thumb')  }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">{{property.title}}</a>
        </h5>
        <p class="card-text">{{property.surface}}  m² -  {{property.city}}  ({{property.postalCode}})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">{{property.formattedPrice}} FCFA
        <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}"><button type="button" class="btn btn-info">Voir les détails</button></a>
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Agence immobilière Camer' %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			{{ form_start(form)}}
			<div class="form-row alin-items-end">
				<div class="col">
					{{ form_row(form.minSurface) }}
				</div>
				<div class="col">
					{{ form_row(form.maxPrice) }}
				</div>
				<div class="col">
					{{ form_row(form.options) }}
				</div>
				<div class="col">
					{{ form_row(form.address, {id: 'search_address'} ) }}
				</div>
				<div class="col">
					{{ form_row(form.distance) }}
				</div>
				<div class="col">
					<div class="form-group">
					<button class="btn btn-primary">Rechercher</button></div>
				</div>
			</div>

			{{ form_end(form)}}

		</div>
	</div>

	<div class="container text-center m-t-5">
		<h1 class="BiensApplication">Voir tous les biens de l'application</h1>

		<div class="row">
			{% for property in properties%}
			<div class="col-md-4">
				{% include ('property/_property.html.twig') %}
			</div>
			
			{% endfor %}
		</div>
		<div class="pagination justify-content-center">{{ knp_pagination_render(properties) }}</div>
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">

      {% for message in app.flashes('success') %}
         <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4 class="text-center messageFlash">{{message}} ☺ </h4>
        </div>
     {% endfor %}

     {% if not form.vars.valid  %}
            <div class="alert alert-danger">
               <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4 class="text-center messageFlash">Oops attention, Veuillez bien remplir le formulaire ✍</h4> 
            </div>
    {% endif %}
                  <div class="DetailBien">Les informations détaillées du bien</div>
            <div class="row">
                <div class="col-md-8">
                    <div data-slider>
                        {% if property.pictures is empty %}
                        <img  src="{{ '/images/empty.jpg' | imagine_filter('medium')  }}" alt="card-img-top"
                            style="width: 100%; height: auto;">
                        {% else %}
                        {% for picture in property.pictures %}
                        <img src="{{ vich_uploader_asset(picture, 'imageFile')  | imagine_filter('medium') }}" alt="card-img-top"
                            style="width: 100%; height: auto;">
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <h5 class="titleProperty">{{ property.title}}</h5>
                    <h2>{{ property.rooms}} pièces - {{ property.surface}} m²</h2>
                    <div class="text-primary" style="font-size: 2rem;font-weight: bold;">{{property.FormattedPrice}} FCFA / Mois</div>
                    <a href="#" class="btn btn-primary" rel="contacter le responsable" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}> Contacter le responsable </a>
                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %} >
                         {{ form_start(form) }}
                         <div class="row">
                             <div class="col">{{ form_row(form.firstname) }}</div>
                             <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>

                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form)}}
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div class="container mt-4">
    <h2 class="Description">Description : </h2>
        <h5 class="description">
            {{ property.description | nl2br }}
        </h5>

        <div class="row">
            <div class="col-md-8">
                <h2 class="caractBiens">Caractéristiques du bien</h2>
                <table class="table table-bordered table-dark">
                    <tr>
                        <td class="infoCarac">Surface habitable</td>
                        <td>{{ property.surface}} m²</td>
                    </tr>
                    <tr>
                        <td class="infoCarac">Nombres de pièces</td>
                        <td>{{ property.rooms}}</td>
                    </tr>
                    <tr>
                        <td class="infoCarac">Nombre de Chambres</td>
                        <td>{{ property.bedrooms}}</td>
                    </tr>
                    <tr>
                        <td class="infoCarac">Niveau d'étage</td>
                        <td>{{ property.floor}}</td>
                    </tr>
                    <tr>
                        <td class="infoCarac">Type de chauffage</td>
                        <td>{{ property.heatType}}</td>
                    </tr>
                </table>

            </div>
            <div class="col-md-4">
                <h2 class="caractBiens">Les options du bien</h2>
                <ul class="list-group OptionsBiens ">	
                    {% for option in property.options %}
                    <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
            <div>
                <h2 class="geolocalisation">La Géolocalisation</h2>
            </div>
        <div id="map" style="width: 100%; height: 400px;" data-lat="{{ property.lat }}" data-lng="{{ property.lng}}">
        </div>
	</div>
{% endblock %}